### ISSUE TITLE
price matching

### ISSUE THREAD

**Issue by shawnmitchell** [PavlosSakoglou/Exchange-Matching-Engine-Emulation#1]
A trade should only take place if the best bid >= best offer. If best bid > best offer the price of the trade is determined by the price of the resting order (the one that arrived first).

**Comment by psakoglou** [comment]
I added the following code instead of averaging the trade price in the Exchange.cpp's matching engine implementation, before the quantity check condition. The submit_id is the exact timestamp of submission as a long long of microseconds.

`if (buy_price < sell_price)
	continue;

double trade_price = 0.0;
if (buy_price > sell_price) // best bid  >= best offer
	if (buy_order.submit_id < sell_order.submit_id) // if buy order arrived first, has smaller timestamp
		trade_price = buy_price;
	else
		trade_price = sell_price;`
